kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: snapshot-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller-runner
      containers:
        - name: snapshot-controller
          image: snapshot-controller
          imagePullPolicy: Always
          args:
            - "-cloudprovider=gce"
        - name: snapshot-provisioner
          image: snapshot-provisioner
          imagePullPolicy: Always
          args:
            - "-cloudprovider=gce"
